# Timber Config

# Specify the folder name of each world where Timber should work on.
worlds:
- world
- anotherworld

# Makes leaves chops aswell when chops down trees
leaves: true

#Tools This plugin will work for. if a tool name is not there it wont work. Coming soon!
toolsallowed:
- "Wooden Axe"
