# Timber Config

# Add the names of the worlds where Timber should work.
# Specify the folder name of each world.
worlds:
- world

# Send a message to the player when they cut down a tree.
# Use {count} to display the number of logs chopped.
# Use & for colors
message: The tree you just cut down contains {count} logs.